clearlinux/cloud-native-setup

clr-k8s-examples/README.md, clr-k8s-examples/create_stack.sh, clr-k8s-examples/reset_stack.sh, clr-k8s-examples/setup_system.sh
Added an option to do minimal install. Default is all
=> Re-organized and formatted the scripts

clr-k8s-examples/README.md
Update README to call out how to try firecracker workloads.
=> Firecracker: Update README

clr-k8s-examples/9-multi-network/Dockerfile, clr-k8s-examples/9-multi-network/README.md, clr-k8s-examples/9-multi-network/multus-conf.yaml, clr-k8s-examples/9-multi-network/multus-sriov-ds.yaml, clr-k8s-examples/9-multi-network/sriov-conf.yaml, clr-k8s-examples/9-multi-network/systemd/sriov.service, clr-k8s-examples/9-multi-network/systemd/sriov.sh, clr-k8s-examples/9-multi-network/test/bridge/0-bridge-net.yaml, clr-k8s-examples/9-multi-network/test/bridge/1-pod-bridge.yaml, clr-k8s-examples/9-multi-network/test/pod.yaml, clr-k8s-examples/9-multi-network/test/sriov/0-sriov-net.yaml, clr-k8s-examples/9-multi-network/test/sriov/1-pod-sriov.yaml
Fixes: #16 This set of yamls installs multus-cni, sriov-cni and sriov-device-plugin 
=> Adding multus and sriov artifacts

clr-k8s-examples/Vagrantfile
=> Enable kubectl autocompletion by default in the VMs

clr-k8s-examples/tests/test-autoscale.sh
=> Make script executable and qualify run as pod

clr-k8s-examples/setup_kata_firecracker.sh
=> Check crio.conf before copying

clr-k8s-examples/setup_kata_firecracker.sh
=> Fix for duplicate lifecycle entry in crio.conf

clr-k8s-examples/9-multi-network/README.md
Add steps to show use of helper scripts
=> Update multi-network readme

clr-k8s-examples/8-kata/deploy/kata-cleanup.yaml, clr-k8s-examples/8-kata/deploy/kata-deploy.yaml, clr-k8s-examples/8-kata/deploy/kata-rbac.yaml, clr-k8s-examples/create_stack.sh, clr-k8s-examples/setup_kata_firecracker.sh
Resolves: #38 
TODO:
Fix FC failing
```
NAME                                   READY   STATUS              RESTARTS   AGE
php-apache-kata-fc-6c6f484c4b-s5rz7    0/1     ContainerCreating   0          4m45s
php-apache-kata-qemu-bc4c55994-4vh4b   1/1     Running             0          4m45s
php-apache-runc-7cc9dcb54f-4sv2c       1/1     Running             0          4m45s
test-cpumanager-kata                   0/1     Completed           0          4m45s
test-cpumanager-runc                   0/1     Completed           0          4m45s
```
```
Warning  FailedCreatePodSandBox  8s (x5 over 82s)  kubelet, clr-01    Failed create pod sandbox: rpc error: code = Unknown desc = container create failed: Failed to check if grpc server is working: context deadline exceeded
```
Signed-off-by: …
=> Use kata-deploy to install and configure kata

clr-k8s-examples/Vagrantfile
Disable proxy setup if the host does not have proxy setup in
the enviornment variables
=> Disable proxy

clr-k8s-examples/README.md
=> Fix readme to add k8s version dependency

clr-k8s-examples/Vagrantfile
=> Download OVMF if it doesn't exist

clr-k8s-examples/README.md
Add docuementation to use ./clr-k8s-examples/reset_stack.sh help
=> README: update flavor setup information.

clr-k8s-examples/create_stack.sh
General fixes to make my vim mark less warnings using shellcheck
=> create_stack: quote variables to avoid code expands

clr-k8s-examples/Vagrantfile, clr-k8s-examples/setup_system.sh
We are picking the major working box version in Vagrantfile and granular clear version in setup_system.sh
until we figure out CI
=> Pinning to working box version and clear version

clr-k8s-examples/setup_system.sh
=> Add swupd update back

metrics/report/README.md, metrics/report/grabdata.sh, metrics/report/makereport.sh, metrics/report/report_dockerfile/Dockerfile, metrics/report/report_dockerfile/genreport.sh, metrics/report/report_dockerfile/metrics_report.Rmd, metrics/report/report_dockerfile/scaling.R
Add the first basic report generator code, utilising R, Rmarkdown
and pandoc to do the data processing and pdf report generation.
Fixes: #121
=> metrics: Add the start of the local report generator

metrics/report/report_dockerfile/scaling.R
This is attempting to improve the information presentation with larger data sets.
I feel that the data points are extremely important and skipping them in larger data sets is problematic. So skip_points was stripped out and points are incorporated into the three graphical charts.
This is becoming too much information for one page and I think my next step will be to split the graphs across pages.
=> tuning node dataset charting, removing skip_points

clr-k8s-examples/Vagrantfile
proxy_ip_list variable had scope issues, used as global variable
initially then as a local variable. Changed all to global.
resolves #133 
Signed-off-by: root <root@csterret-desk1.amr.corp.intel.com>
=> Fixed vagrant issue with proxy

metrics/report/report_dockerfile/scaling.R
All graphs were starting with 1. The zero index is the system baseline. So moved to starting with 0.
Fixed the calculations to account for the baseline index, so n-1 as the denominator.
Also accounting for when STEP != 1 in both the graphs and the stats.
=> fixing indexing, start with 0

metrics/report/report_dockerfile/parallel.R
Take into account 'steps' on x-axis plots.
Suppress warnings from geom_smooth.
=> metrics: parallel plot cleanups

clr-k8s-examples/create_stack.sh
=> Fix script error cause of missing variables

metrics/README.md
The README has not kept upto date with the code. Update to make it
more useful, but try to keep fairly neutral so it does not rot so
fast.
=> metrics: README: update to be accurate and more descriptive

metrics/scaling/k8s_scale.sh
Also remove trailing whitespace
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> metrics: scaling: require jq is installed

clr-k8s-examples/create_stack.sh, clr-k8s-examples/node-problem-detector/overlays/v0.6.6/kustomization.yaml, clr-k8s-examples/node-problem-detector/overlays/v0.6.6/patch_configmap_mce-monitor.yaml, clr-k8s-examples/node-problem-detector/overlays/v0.6.6/patch_configmap_rules.yaml
Adds the node problem detector 
=> Add node problem detector

clr-k8s-examples/7-rook/overlays/v1.1.0/kustomization.yaml, clr-k8s-examples/7-rook/overlays/v1.1.0/patch_cephcluster.yaml, clr-k8s-examples/create_stack.sh, clr-k8s-examples/hack/ceph_status.sh
Adds handling for CSI version of Rook to create_stack.sh
Closes #30
=> Update to rook v1.1.0

clr-k8s-examples/6-metal-lb/overlays/v0.8.1/kustomization.yaml, clr-k8s-examples/6-metal-lb/overlays/v0.8.1/patch_configmap.yaml, clr-k8s-examples/create_stack.sh
This updates metallb to v0.8.1.
=> Update metallb to v0.8.1

clr-k8s-examples/8-kata/overlays/1.8.2-kernel-config/kustomization.yaml, clr-k8s-examples/create_stack.sh
=> Update kata to v1.8.2

clr-k8s-examples/vagrant.md
This change add's a note to specify env vars to use desired
CPU and Memory for individual VM's as required
Signed-off: Syed Ahsan<syed.ahsan.shamim.zaidi@intel.com>
#177
=> Adding instructions to modify CPU/MEMORY for VM's

clr-k8s-examples/0-canal/overlays/v3.9/kustomization.yaml, clr-k8s-examples/create_stack.sh
This replaces previous canal v3.3.
=> Update canal to v3.9

clr-k8s-examples/1-core-metrics/overlays/v0.3.5/kustomization.yaml, clr-k8s-examples/create_stack.sh
Upgrade metrics to v0.3.5 for k8s 1.16
=> Update metrics to v0.3.5

metrics/README.md
The guide include scaling basic execution and result reporting.
=> Add step-by-step guide for scaling execution into README file.

metrics/lib/common.bash, metrics/scaling/bb.json.in, metrics/scaling/bb.yaml.in, metrics/scaling/common.bash, metrics/scaling/k8s_parallel.sh, metrics/scaling/k8s_scale_nc.sh
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> Add configurable scaled pod workload for latency tests

clr-k8s-examples/DEVELOP.md
This adds details about shfmt and shellcheck settings.
=> Add section about code conventions to DEVELOP.md

metrics/scaling/k8s_scale_nc.sh
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>
=> scaling: fix syntax error in results/k8s-scaling-nc.json

clr-k8s-examples/7-rook/overlays/v1.1.1/kustomization.yaml, clr-k8s-examples/7-rook/overlays/v1.1.1/patch_cephcluster.yaml, clr-k8s-examples/create_stack.sh
=> Update rook to v1.1.1

clr-k8s-examples/create_stack.sh, clr-k8s-examples/kubeadm/base/kubeadm.yaml, clr-k8s-examples/kubeadm/base/kustomization.yaml, clr-k8s-examples/kubeadm/high-pod-count/cluster-config.json, clr-k8s-examples/kubeadm/high-pod-count/kubelet-config.json, clr-k8s-examples/kubeadm/high-pod-count/kustomization.yaml
This change splits current configuration sections of kubeadm.yaml in single files in order to make it easier customizations using kustomize. create_stack script now build a new on the fly kubeadm.yaml file just before to execute kubeadm init.
=> Kustomize kubeadm.yaml config file

clr-k8s-examples/Vagrantfile
This adds passing HIGH_POD_COUNT on to setup_system.sh
=> Add vagrantfile support for HIGH_POD_COUNT config

clr-k8s-examples/README.md, clr-k8s-examples/create_stack.sh
This change adds Cilium to create_stack script, and uses crio
by default unless the user otherwise speicify
Signed-Off: Syed Ahsan <syed.ahsan.shamim.zaidi@intel.com>
#179
=> Adding Cilium to create_stack

clr-k8s-examples/create_stack.sh, clr-k8s-examples/node-feature-discovery/overlays/v0.4.0/kustomization.yaml
This adds the node-feature-discovery component.
Partialy implements #32
=> Add node-feature-discovery

clr-k8s-examples/create_stack.sh
This patch adds Global functions outside and kustomize
the create_stack.sh file.
#241
=> Adding Global Functions outside + Kustomization

clr-k8s-examples/0-cilium/overlays/v1.6/kustomization.yaml, clr-k8s-examples/create_stack.sh
This patch adds kustomization path and file for Cilium
=> Adding Kustomization for Cilium

clr-k8s-examples/8-kata/overlays/1.8.2-kernel-config/kustomization.yaml
=> Kustomize kata-deploy image to stable version

clr-k8s-examples/reset_stack.sh
Fixes #201 
Signed-off-by: Khanak Nangia khanak.nangia@intel.com
=> Cleaning containerd data in reset_stack script

clr-k8s-examples/5-ingres-lb/overlays/nginx-0.25.0/kustomization.yaml, clr-k8s-examples/7-rook/overlays/v0.8.3/patch_operator.yaml, clr-k8s-examples/9-multi-network/multus-sriov-ds.yaml, clr-k8s-examples/DEVELOP.md, clr-k8s-examples/admit-kata/deploy/webhook-registration.yaml.tpl, clr-k8s-examples/admit-kata/deploy/webhook.yaml, clr-k8s-examples/tests/deploy-svc-ing/test-ingress-kata.yaml, clr-k8s-examples/tests/deploy-svc-ing/test-ingress-runc.yaml
Fixes #220 
Signed-off-by: Khanak Nangia khanak.nangia@intel.com
=> Updating the deprecated beta workload APIs for K8s v1.16

metrics/report/report_dockerfile/collectd_scaling.R
Since collectd is started before the pods are launched and
shutdown after the last pod is launched, we gather data outside
the pod launch window which can adversely influence the per pod
launch stats. This is especially true after the last pod launches
as all the pods are then deleted before collectd stops collecting
metrics.
This patch isolates the collectd data used to only
coincide with the pod launch window.
An additional change in this patch is to improve the secondary
y axis scaling. There was an ill-advised check in previously to
force the scale to be at least 1. This does not work well when
the pod number is significantly higher than say 100 (the max
possible cpu idle value).
This patch changes the scaling to be across all data to be graphed.
The special condition remains for …
=> disregard collectd tail data from stats

clr-k8s-examples/containerd_devmapper_setup.sh
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
=> set the snapshotter to devmapper in setup script

metrics/README.md, metrics/scaling/README.md, metrics/scaling/k8s_scale_net.sh
Improve the documentation for the metrics subsystem.
- Improve the top level README
- move the scaling details into the scaling subdir, rewrite and embellish.
=> metrics: improve documentation

clr-k8s-examples/README.md
=> Update README to take not of k8s-migration package

clr-k8s-examples/0-canal/overlays/v3.22/kustomization.yaml, clr-k8s-examples/0-cilium/overlays/v1.9.13/kustomization.yaml, clr-k8s-examples/0-flannel/overlays/v0.16.3/kustomization.yaml, clr-k8s-examples/create_stack.sh
=> Update CNIs to versions that work well with 1.20.X of Kubernetes

clr-k8s-examples/create_stack.sh
=> fix canal download URL

clr-k8s-examples/create_stack.sh
=> Fix bash command to check prometheus crds

clr-k8s-examples/5-ingres-lb/overlays/controller-v1.3.0/kustomization.yaml, clr-k8s-examples/create_stack.sh
=> Revert check for prometheus deployment and update nginx

clr-k8s-examples/create_stack.sh
=> Add storage back to all function
