clearlinux/cloud-native-setup

clr-k8s-examples/3-efk/fluentd-es-configmap.yaml

We see kata logs with `SYSLOG_IDENTIFIER:kata-runtime` under
`_SYSTEMD_UNIT:crio.service` in kibana. Need to verify if this holds
good for `SYSLOG_IDENTIFIER=kata-proxy` and `SYSLOG_IDENTIFIER=kata-shim`

Scrape crio logs, includes kata logs too

---

clr-k8s-examples/setup_system.sh

Improve some of the file checks to avoid either duplicating items that may already exist or
trying to edit files that don't exist.
Reduce the stdio noise output by using `cat` instead of `tee` for the sudo file writes.
Restart the system services after we may have changed their settings.
Clean up a bit of whitespace.

setup_system: bolster checks, cleanup output

---

clr-k8s-examples/kubeadm.yaml

clearlinux-pkgs/kubernetes installs kubeadm kubelet of the same version
and kubeadm uses/fallsback to stable branch of its major+minor version when
generating kubernetes component manifests if none is provided. This
helps with staying upto date with any fixes without any further
modifications
```
vagrant@clr-01 ~ $ bash /vagrant/create_stack.sh
I1207 21:37:25.285850   16086 version.go:236] remote version is much newer: v1.13.0; falling back to: stable-1.12
[init] using Kubernetes version: v1.12.3
```

Do not pin kubernetes version in kubeadm config

---

clr-k8s-examples/kubeadm.yaml
clr-k8s-examples/tests/test-cpumanager-runc.yaml

Fixes: #8, #16
Setting CPUManagerPolicy=static allows `Guaranteed` QoS class workloads to
get cpu isolation and affinity benefits.
https://kubernetes.io/blog/2018/07/24/feature-highlight-cpu-manager/
Setting reserved compute resources for system processes and critical
kube components prevents from DoS'ing the compute node.
https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/

Set CPUManagerPolicy=static, reserve compute resources

---

clr-k8s-examples/8-kata/fire-runtimeClass.yaml
clr-k8s-examples/README.md
clr-k8s-examples/Vagrantfile
clr-k8s-examples/create_stack.sh
clr-k8s-examples/setup_firecracker.sh
clr-k8s-examples/setup_system.sh
clr-k8s-examples/tests/test-deploy-fire.yaml

Initial support for firecracker configuration on Clearlinux.
This is a little bit complicated due to CRIO requiring a
disk or partition to use devicemapper.
To test 
```
kubectl apply -f 8-kata/fire-runtimeClass.yaml
kubectl apply -f tests/test-deploy-fire.yaml
```

Initial support for firecracker configuration on Clearlinux

---

clr-k8s-examples/admit-kata/webhook.yaml

The kata-webhook is now hosted within the Kata repository.
Switch to using the kata generated images
https://cloud.docker.com/u/katadocker/repository/docker/katadocker/kata-webhook-example
https://github.com/kata-containers/tests/tree/master/kata-webhook

kata-webhook: Change location to katadocker

---

clr-k8s-examples/Vagrantfile

The parent box is already downloading the OVMF firmware.
Just use the firmware that is already downloaded.

Downloading OVMF causes issues with libvirt

---

clr-k8s-examples/setup_kata_firecracker.sh

Disable devicemapper udev sync. Without this the storage device
will not be discovered post system reboot

Disable devicemapper udev sync

---

clr-k8s-examples/Vagrantfile

This was the error
```
==> clr-01: Rsyncing folder: /home/stack/delete/cloud-native-setup-sai/clr-k8s-examples-2/ => /home/clear/clr-k8s-examples-2
There was an error when attempting to rsync a synced folder.
Please inspect the error message below for more info.
Host path: /home/stack/delete/cloud-native-setup-sai/clr-k8s-examples-2/
Guest path: /home/clear/clr-k8s-examples-2
Command: "rsync" "--verbose" "--archive" "--delete" "-z" "--copy-links" "--no-owner" "--no-group" "--rsync-path" "sudo rsync" "-e" "ssh -p 22 -o LogLevel=FATAL   -o ControlMaster=auto -o ControlPath=/tmp/vagrant-rsync-20190226-10142-qkicdt -o ControlPersist=10m  -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i '/home/stack/.vagrant.d/insecure_private_key'" "--exclude" ".vagrant/" …
```

Hotfix for rsync update in new clear (box?)

---

clr-k8s-examples/7-rook/000-operator.yaml
clr-k8s-examples/7-rook/001-cluster.yaml
clr-k8s-examples/README.md
clr-k8s-examples/admit-kata/webhook-registration.yaml
clr-k8s-examples/tests/deploy-svc-ing/test-deploy-kata-qemu.yaml

The admission controller is now able to access full context. Hence explicit tagging of pod manifests to exclude them from kata is no longer required.
Additonally, we only support kubernetes versions with support for runtimeClass.  Remove the legacy annotations to reduce confusion.

 Update webhook setup and documentation

---

clr-k8s-examples/9-multi-network/multus-sriov-ds.yaml

In case of containerd there is no need to restart. Restart for crio is needed
when it manages the networks ns lifecycle. Removed the kubelet stop step which
was a leftover from earlier device plugin install.

Do not restart containerd, remove stop kubelet

---

clr-k8s-examples/kubeadm.yaml
clr-k8s-examples/tests/cpumanager/test-cpumanager.yaml.tmpl

This is finally supported in Kata 1.6
Update memory limit for kata to run in guaranteed test case
Resolves #71 

Turn on static policy for CPU manager

---

clr-k8s-examples/8-kata/deploy/kata-cleanup.yaml
clr-k8s-examples/8-kata/deploy/kata-deploy.yaml

We updated to use containerd v2 shim - pull in latest from master
Noticed there's been a discrepancy in the yaml between Kata and this repo for /bin/bash v. bash.  PTAL at this @krsna1729 ?

kata-deploy: update to match what's on Kata master

---

clr-k8s-examples/create_stack.sh

CRD was removed as part of 1.14 update. Missed update to create_stack
Fixes: #84

Remove applying runtimeclass CRD

---

clr-k8s-examples/setup_system.sh

Calico requires the default reverse path forwarding to be either 0 (no
validation) or 1 (strict validation). The default value of 2 (loose
validation) prevents calico from completing the setup and the pod is
always stuck getting ready.

Set reverse path forwarding to strict.

---

clr-k8s-examples/create_stack.sh

Add more subcommands to to increase granularity
init: start cluster
cni: setup network
This functionality already existed, we only handle
subcommands in a more dynamic way.
By default the script not run `all` anymore but shows help.
```
./create_stack.sh
Usage: ./create_stack.sh [subcommand]
Subcommands:
all:            minimal + storage + monitoring + miscellaneous
cni:            Setup network for running cluster
help:           show this message
init:           Only inits a cluster using kubeadm
minimal:        init + cni +  kata + metrics
```
Fixes: #92

create_stack: Add init and cni subcommands

---

clr-k8s-examples/kubeadm.yaml
clr-k8s-examples/reset_stack.sh

kubeadm autodetects the socket path based on defaults from well known
CRI servers.

stack: dont provide CRI socket

---

clr-k8s-examples/reset_stack.sh

- If stop CRI service if is running
- Restart the CRI service only if enabled
- Do not enable crio on reset_stack.sh this should be only part of the
setup.

reset_stack: stop containerd and crio

---

clr-k8s-examples/setup_system.sh

Currently net.ipv4.conf.all.rp_filter is set to 2 in Clear and
calico-node fails to come up unless that value is either 0 or 1.

calico-node fails to come up cause of all.rp_filter

---

clr-k8s-examples/setup_system.sh

ClearLinux now has cri-o version 1.14.1 which allows multiple plugin
locations and also creates /opt/cni/bin by default. We no longer need
the hacks for them

cri-o update fixes

---

clr-k8s-examples/0-canal/canal.yaml
clr-k8s-examples/setup_system.sh

Modifying rp_filter setting on host seems to be causing a routing issue
when connecting to a pod from remote node. Until we figure out the best
way to solve the issue, we are configuring canal to ignore default
setting of 2
Fixes: #102

Configure canal to ignore rpf instead of host

---

clr-k8s-examples/Vagrantfile
clr-k8s-examples/setup_system.sh

Clearlinux release 30270 is now a known good version compatible
with kubernetes.
RuntimeName:  cri-o
RuntimeVersion:  1.14.4
RuntimeApiVersion:  v1alpha1
Kubernetes v1.15.0
runc version 1.0.0-rc5
spec: 1.0.0
systemd 242 (242)
+PAM +AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 -IDN -PCRE2 default-hierarchy=legacy
Kernel: 4.19.57-60.lts2018

Versioning: Update clearlinux version to 30270

---

clr-k8s-examples/Vagrantfile
clr-k8s-examples/containerd_devmapper_setup.sh
clr-k8s-examples/setup_system.sh

This setup scripts have been using cri-o all this while as the pod
controller/manager system. Recent past cri-o has had some issues with
kata-deploy (A restart of the service will not be able to re-connect
with the existing pods and restart all of them including kata-deploy,
which will hit an endless loop). Moving to containerd as default for
now.
Firecracker cannot be used with a released version of containerd as
there is no default block based snapshotter available today. If you wish
to use cri-o make sure you set `RUNNER=crio` in your environment prior
to using the script.

Move to containerd as the default manager

---

metrics/README.md
metrics/lib/common.bash
metrics/lib/json.bash
metrics/lib/kata-common.bash
metrics/scaling/bb.yaml.in
metrics/scaling/k8s_scale.sh
metrics/scaling/stats.yaml

Initial commit of metrics for scaling

---

metrics/scaling/bb.json.in
metrics/scaling/bb.yaml.in
metrics/scaling/k8s_scale.sh

Adds option to use_api for launch calls (currently). Fixed missing tab indent issues. Also supports starting or finding the kubectl proxy process and using that address and port for API calls.
<s>Eventually, I think we'll want to not just update the same deployment, but rather launch separate deployments so we can track shutdown time. I have a version of that working too, but this is a start.</s>
After playing more with OpenFaaS, I think we should stick with this model. It more closely duplicates their model.
The other option is https://github.com/dklyle/cloud-native-setup/tree/use-api-launch-2, but I think we can just track pods in this model.

Add option to use API to launch

---

metrics/scaling/k8s_scale.sh

We need to check when we are launching our first instance of a
deployment when using the k8s API directly, as we have to modify
the URL for the first instance. Rather than check for '1', let's
check for 'STEP', as technically you can run the loop starting at
a non-1 index (particularly useful to run with NUM_PODS==STEP, as
you then get a 'single shot' test of 'n' containers).

metrics: scaling: change check for 'first deploy' to non-1 indexed

---

metrics/lib/json.bash
metrics/report/report_dockerfile/scaling.R
metrics/scaling/k8s_scale.sh
metrics/scaling/stats.yaml

This adds the stats pod via a daemonset. stats are collected for all nodes after each pod launch. The json output structure was altered to support this new data. To support the new structure, nested array support in json.bash was added. This only supports one layer of nesting. I looked at generalized nesting support, but 2D data structures in bash leaves a lot to be desired. 
The reporting in R has also been updated to support displaying cpu and memory for all nodes on a cluster for all tests being compared. The page layout was also changed to be one chart per row, rather than 2 as the charts ended up rather small for the greater detail. In the future, we'll likely want to increase the height of the rows with graphs.

Multinode support

---

metrics/report/report_dockerfile/scaling.R
metrics/scaling/bb.json.in
metrics/scaling/bb.yaml.in
metrics/scaling/k8s_scale.sh
metrics/scaling/stats.yaml

Now excluding nodes with NoSchedule taints from being included in pod/CPU and pod/GB calculations.
Also added some grace period tuning. pods in the stats daemonset now shut down instantly. Grace period for pods in the workload deployment is configurable via env variable, grace.

excluding NoSchedule nodes from workload calculations

---

clr-k8s-examples/7-rook/overlays/v1.0.3/kustomization.yaml
clr-k8s-examples/7-rook/overlays/v1.0.3/patch_cephcluster.yaml

Fix issue where OSDs not creating without extra available partitions. Now all OSDs will be filesystem based.

Use directories instead of partitions for rook

---

metrics/lib/json.bash
metrics/scaling/k8s_parallel.sh
metrics/scaling/k8s_scale.sh

A small set of patches to:
- fix parallel test wrt grace
- add timestamps to individual metrics
- move default runtime to 'default' instead of ''
- whitespace

metrics: small fixes and improvements

---

metrics/report/report_dockerfile/dut-details.R
metrics/report/report_dockerfile/metrics_report.Rmd

Add a table to the end of the report showing useful details about
the systems that were under test - version numbers, resources etc.
Fixes: #145

metrics: report: Add system under test details

---

clr-k8s-examples/create_stack.sh

This change will allow the create_stack.sh script to be called to init
the k8s cluster with a user generated bootstrap token and a pre-defined
master_ip. This will allow us to automate initial deployment of cluster
with a known list of IPs

Allow bootstrap token and master_ip to be customizable

---

clr-k8s-examples/setup_system.sh

This udpate allows us to specify an OS specific
include file with function overrides. Useful when using
setup_system.sh on other OSes.

Update setup_system.sh to include alt OS file

---

clr-k8s-examples/Vagrantfile

Removed hardcoded vagrant box version. This change will now
allow the override of the version, or if no override is passed in
it will take the version on the system, or download the latest version.
Signed-off-by: craigsterrett <craig.sterrett@intel.com>

Removed vagrant box pinning

---

metrics/scaling/k8s_scale.sh

bash arrays don't handle hyphens in the index as it treats
a name like "azure-east-1" as 0-0-1, so remove any hyphens in the
node name, will work as long as hyphens aren't the only difference
in node names
Fixes #163

Remove possible hyphens from array index

---

metrics/lib/json.bash

Use `tr` rather than `sed` for doing the line/whitespace conversions
on the JSON stream, if asked. Slightly more efficient, and we also drop
the wrapping ""'s, to allow the data to land in logstash without error.

metrics: json: use tr for newline/whitespace conversion

---

metrics/report/report_dockerfile/tidy_scaling.R

In the rewrite of the report generation code, we regressed to
using the passed in requested number of pods rather than the
actual. Since we typically attempt to launch more pods than the
system is capable of, the math for the stats are done incorrectly
and misreported.
This changes the behavior back to using the correct value of the
total number of pods launched.
Fixes: #167

Fixing number of pods in report

---

clr-k8s-examples/Vagrantfile

Vagrant file blows up if http_proxy is set but no_proxy is not set. This
was discovered during the testing of the initial patch which was to add
the default CIDR for Vagrant to the no_proxy settings.
Closes issue #136
Signed-off-by: craigsterrett <craig.sterrett@intel.com>

Fixes no_proxy issues with Vagrant file

---

clr-k8s-examples/vagrant.md

Added command for installing unzip bundle since vagrant.sh requires unzip, else it will error out. Similarly, added command for installing rsync bundle, since Vagrantfile requires it. These bundles need to be added explicitly on some clear images. Also, removed the sudo, since running as normal user works fine.

adding detailed instructions for vagrant setup on clear linux

---

clr-k8s-examples/5-ingres-lb/overlays/nginx-0.25.1/kustomization.yaml
clr-k8s-examples/create_stack.sh

Patches HTTP2 CVEs as detailed here http://nginx.org/en/security_advisories.html

Update ingress-nginx to v0.25.1

---

clr-k8s-examples/kubeadm.yaml

Fixes: clearlinux/distribution/issues/1267 (partial)
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>

kubelet: use systemd cgroup driver

---

metrics/scaling/common.bash
metrics/scaling/k8s_parallel.sh
metrics/scaling/k8s_scale.sh
metrics/scaling/k8s_scale_nc.sh

A recent change put global variable declarations in a function,
the variables no longer are globally visible. This change removes
the encapsulation in a function.
Closes: #202

global variables in function aren't global

---

clr-k8s-examples/vagrant.md

#205 This patch fixes the typo in vagrant instructions, it should be
CPUS.

Typo in vagrant instruction

---

clr-k8s-examples/README.md
clr-k8s-examples/setup_system.sh

This change helps with setting up the RUNNER to use crio
by default instead of using containerd. If the user wants
to use containerd, they need to specify when running the
setup_system script.
#181

Setting the RUNNER to use crio

---

clr-k8s-examples/vagrant.md

This patch adds the users to the default group so we dont
have to use sudo to start the vagrant, as using sudo is not
the most optimal route for gems to be properly configured.

Vagrant Libvirt Instructions update

---

clr-k8s-examples/Vagrantfile

Vagrant file also sets a default container engine and runs
setup_system.sh. This was currently setting runner=containerd if RUNNER
environment variable was not set, I changed default to crio
Closes issue #216 
Signed-off-by: craig <craig.sterrett@intel.com>

Changed default container engine to crio

---

clr-k8s-examples/setup_system.sh

There is no need of launching kubelet before kubeadm, giving a confusing launch fail warning message, since kubelet will startup later once we have configured with kubeadm. This PR fixes issue #127 . 
Closing #138 
Signed-off-by: Khanak Nangia khanak.nangia@intel.com

No need of launching kubelet before kubeadm init/join

---

metrics/README.md
metrics/collectd/Dockerfile
metrics/collectd/collectd.bash
metrics/collectd/collectd.conf
metrics/collectd/collectd.yaml
metrics/report/report_dockerfile/collectd_scaling.R
metrics/report/report_dockerfile/dut-details.R
metrics/report/report_dockerfile/metrics_report.Rmd
metrics/scaling/k8s_scale_rapid.sh

This patch adds a new script, scaling/k8s_scaling_rapid.sh, for
launching pods and collecting metrics. The goal is to two fold.
The first goal is improve the required runtime duration of scaling
to large numbers of pods. k8s_scaling.sh can take up to 29 hours
to scale to 2900 pods. The is largely due to the overhead of
collecting system utilization stats after each new pod is launched.
This new script will collect system utilization stats asynchronously.
The second goal is to make it easier to collect additional system
utilization stats by leveraging the plugins supported by collectd.
Instead of using the stats daemon set, a new daemon set
that runs collectd on each node is added. collectd configuration
is handled by collectd/collectd.conf A configmap is added to the
K8s cluster …

Adding support for aysnc metrics via collectd

---

metrics/report/report_dockerfile/metrics_report.Rmd
metrics/report/report_dockerfile/node-info.R

**What**
A final table report gets added into the PDF report for node information details per node.
**Tests**
The changes where tested using two different results, following the next structure:
```
$ tree metrics/results/
metrics/results/
├── Env.R
├── scaling
│   └── k8s-scaling.json
└── scaling-vms
└── k8s-scaling.json
``` 
The final look for the created tables is shown below 🎉 
And the final PDF report is attached too.
[metrics_report.pdf](https://github.com/clearlinux/cloud-native-setup/files/3736493/metrics_report.pdf)

Add extra table about node information into PDF report.

---

metrics/report/report_dockerfile/collectd_scaling.R

The collectd csv plugin starts a new file for each day that data is
being recorded. Currently, collectd_scaling.R only reads from the
first day's file. This leads to incomplete data being rendered in
the report charts. All the data files are collected and present,
they just need to be read.
This patch makes changes to read all the days of collectd data and add
them to the data set.
Closes: #226
Signed-off-by: David Lyle <dklyle0@gmail.com>

handle multiday collectd data

---

clr-k8s-examples/setup_system.sh

Added .svc to the no_proxy in setup_system.sh to keep Kubernetes service
requests from being routed to the proxy. This fixes and issue that
Humberto was seeing in his testing.
Signed-off-by: Craig Sterrett <craig.sterrett@intel.com>

Added .svc to no_proxy

---

clr-k8s-examples/create_stack.sh

When we are using instances in the public cloud, such amazon or azure, we need a way to connect to the public k8s cluster with the public ip or the public name, with this addition we are supporting the ability to add those public values into the k8s certificates in order to can connect from anywhere not only from the private cluster subnet.
example: 
```
export CERT_SANS="34.221.115.244 ec2-34-221-115-244.us-west-2.compute.amazonaws.com"
./create_stack.sh  init
```
```
$kubectl cluster-info
Kubernetes master is running at https://ec2-34-221-115-244.us-west-2.compute.amazonaws.com:6443
KubeDNS is running at https://ec2-34-221-115-244.us-west-2.compute.amazonaws.com:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

Adding Cert sans to kubeadm config

---

clr-k8s-examples/README.md
clr-k8s-examples/Vagrantfile

Updating the default value to 4 CPUS and 8G MEMORY for vagrant VMs. Since running setup_system.sh and create_Stack.sh all is resource intensive and vagrant VMs keep shutting off with less resources.

Increasing the CPUS and MEMORY default value for vagrant VMs

---

clr-k8s-examples/hack/update_checker.sh

This adds a script that parses create_stack for component versions
and URLs and compares them to the latest versions available.

Add update_checker.sh

---

clr-k8s-examples/0-flannel/overlays/16b0fe66285d1ad1f42b154ab852682f6fafb1a7/kustomization.yaml
clr-k8s-examples/create_stack.sh

This patch add's Flannel to CNI, export the environment variable
to use Flannel, and uses crio as default unless the user
specify otherwise.
Signed-Off: Syed Ahsan <syed.ahsan.shamim.zaidi@intel.com>
#190

Adding Flannel to CNI

---

clr-k8s-examples/create_stack.sh

This PR disables the git advice message seen for
each component as its installed.
Signed-off-by: Justin Scott <justin.a.scott@gmail.com>

Disable git checkout advice in create_stack.sh

---

clr-k8s-examples/README.md

With reference to #240 , updating README.md with new increased default values of CPUS and MEMORY for Vagrant VMs.
Signed-off-by: Khanak Nangia khanak.nangia@intel.com

updating readme with increased CPUS and MEMORY value for vagrant VMs

---

clr-k8s-examples/README.md
clr-k8s-examples/setup_system.sh

This adds ability to upgrade/downgrade to desired Clear version.
The default behavior remains unchanged (auto updating to latest)

Add CLRK8S_CLR_VER to setup_system.sh

---

clr-k8s-examples/Vagrantfile

This adds env var to the Vagrantfile so that Clear version can be
specified.

Add CLRK8S_CLR_VER to Vagrantfile

---

metrics/report/report_dockerfile/Dockerfile

A recent change to debian apt repositories led to build errors
for the report container. The error was around stretch release
files. The container image we are based on published an update
which fixes this error. This patch updates to use :latest to
avoid errors when building.
Signed-off-by: David Lyle <dklyle0@gmail.com>

fixing makereport container build

---

clr-k8s-examples/containerd_devmapper_setup.sh

base_image_size is effectively the max size of the thinpool snapshot,
and this is static (does not resize).  If you are running containers
with larger individual layers, this will fail. (elastic is a good test
for this).
The thinpool should be 10GB, not 1GB (to align with the .img's defined
earlier in file).
Fixes: #266
Signed-off-by: Eric Ernst <eric.ernst@intel.com>

devmapper: update to be functional, usable

---

metrics/collectd/collectd.conf

KIND uses the older network interface naming standard. Other
operating system images may as well. Adding support for 'eth'
network interface naming prefix.
Closes #257 
Signed-off-by: David Lyle <dklyle0@gmail.com>

support older network interface naming

---

metrics/collectd/collectd.conf

On some machines the value for hostname, that is used in naming
the csv directory, isn't always determined by collectd to be
localhost. The scaling code assumes it will always be localhost.
This patch specifies the hostname to be localhost.
Signed-off-by: David Lyle <dklyle0@gmail.com>

Specify hostname for file name for collectd

---

clr-k8s-examples/setup_system.sh

The sed command for updating no-proxy settings in the proxy.sh file was
not working. I made it match the above command which was working for
/etc/environment.
Signed-off-by: Craig Sterrett <craig.sterrett@intel.com>

Fixed code for no_proxy in setup_system.sh

---

clr-k8s-examples/setup_system.sh

Adding non-routable IPs to the no_proxy, non-routable addresses will
never go out the proxy, and are used as internal IPs by VM's running
cloud-native setup. Without the addition of the IP's in no_proxy,
kubernetes nodes will not be able to communicate to the Kubernetes IP as
the traffic will be routed out the proxy server.
Signed-off-by: Craig Sterrett <craig.Sterrett@intel.com>

Adding non-routable IPs to no_proxy

---

metrics/README.md
metrics/collectd/collectd.bash
metrics/lib/common.bash
metrics/lib/cpu-load.bash
metrics/lib/cpu-load.md
metrics/lib/cpu_load_daemonset.yaml.in
metrics/scaling/k8s_parallel.sh
metrics/scaling/k8s_scale.sh
metrics/scaling/k8s_scale_nc.sh
metrics/scaling/k8s_scale_rapid.sh

Add a `stress-ng` based cpu load generator daemonset capability to the framework.
To enable this option across all tests, re-jig the framework so all tests call a common single code path for setup and teardown, thus affording us the ability to enable generic features (like the cpu-load daemonset, but also v.likely the collectd daemonset as well, and future features).

metrics: enable optional cpu-stress cluster load generator

---

clr-k8s-examples/README.md
clr-k8s-examples/create_stack.sh
clr-k8s-examples/setup_system.sh

Earlier there was confusion between CLRK8S_RUNNER and RUNNER in
setup_system.sh and create_stack.sh script, this patch fixes this
and now the variable can either be RUNNER/CLRK8S_RUNNER.
Signed-off: syed.ahsan.shamim.zaidi@intel.com 
#272

Using consistent ENV variable for RUNNER

---

metrics/scaling/k8s_scale.sh
metrics/scaling/k8s_scale_nc.sh

Under some circumstances, the pod_per_gb value would come out as <0,
and be generated without any leading 0's (such as `.14` rather than
`0.14`). This is not valid JSON, and would break the report generation
parsing in R.
Use `printf` to force a leading 0 prefix onto the value.

metrics: make pods_per_gb valid JSON

---

metrics/report/makereport.sh

This is in order to avoid tty-related issues in our CI systems
which by default is not supporting tty. With this change we'll
avoid the following faling report's generation `docker run` command.
```
the input device is not a TTY
```
Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>

scaling: Remove tty parameter in report's generation cmd

---

metrics/report/report_dockerfile/collectd_scaling.R
metrics/report/report_dockerfile/pdf.Rmd
metrics/report/report_dockerfile/tidy_scaling.R

A small set of improvements to help graph readability in the report:
- move the legends under the graphs, which allows the graphs to be wider
- reduce the page margins in the pdf, which allows the graphs to be wider still
- improve the lhs y axis for the interface drop/error graphs so the labels look sensible.

metrics: graph improvements

---

metrics/lib/common.bash
metrics/scaling/common.bash
metrics/scaling/k8s_scale_net.sh
metrics/scaling/net-serve.json.in
metrics/scaling/net-serve.yaml.in

**What**
This in work branch has:
- The required file templates from which the http server is going to be created, which includes a readiness probe and a minimum success threshold for it.
- Only measuring time to pod network, and such measurements gets written into the `json` output file.
- The metrics reporting doc will be address in a different PR.
**Testing done**
At the moment these changes are been tested on a all-in-one Kubernetes cluster and getting the next output:
```
cloud-native-setup/metrics/scaling $ NUM_DEPLOYMENTS=2 grace=0 ./k8s_scale_net.
sh
INFO: Initialising
command: bc: yes
command: jq: yes
INFO: Checking Kubernetes accessible
INFO: 1 Kubernetes nodes in 'Ready' state found
starting kubectl proxy
Starting to serve on 127.0.0.1:8090
INFO: Running test
INFO: Testing …
```

 Add time to pod network metric.

---

metrics/scaling/common.bash
metrics/scaling/k8s_scale_net.sh

Some CNIs takes longer for its related deployments to become ready, that
is why `proc_wait_time` needs to be customized. Now `proc_wait_time` can
be set at execution time and has a default value too for time to pod network test harness.

Make and rename net server process variables configurable

---

clr-k8s-examples/kubeadm.yaml

Update kubeadm.yaml to 1.17 version

---

clr-k8s-examples/setup_system.sh

Running setup_system.sh on a system setting the OS version to keep setup_system from upgrading the OS causes an error because a package has been removed. Need to add the --force flag to the
sudo swupd repair -m "${CLR_VER}" --picky command
Closes issue #297

Added --force flag to swupd repair command

---

clr-k8s-examples/setup_system.sh

Modified setup_system.sh to use Systemd level proxy instead of per
service proxy.
Tested create_stack all with defaults and ran Sonobuoy successfully against change both behind proxy and without proxy.
Closes issue #307
Signed-off-by: Craig Sterrett <craig.Sterrett@intel.com>

Modified setup_system to use Systemd level proxy

---

clr-k8s-examples/9-multi-network/cni/vfioveth

```
5: s1u-vdev@s1u: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
link/ether d2:8e:b5:97:4b:de brd ff:ff:ff:ff:ff:ff
6: s1u@s1u-vdev: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
link/ether ee:b6:c7:9a:0c:a6 brd ff:ff:ff:ff:ff:ff
alias 0000:04:10.4
```

Update vfioveth CNI to add VF device id as alias

---

clr-k8s-examples/create_stack.sh

The metrics-server package has moved out of the kubernetes incubator
github location and is now in the sigs location.
Closes issue #322 
Signed-off-by: Craig Sterrett <craig.Sterrett@intel.com>

Updated metrics github location

---

metrics/report/report_dockerfile/Dockerfile

This PR uses a specific version of rocker/tidyverse as the latest version
does not have the latex-xcolor package which makes impossible to create
the metrics report.
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

metrics: Use a specific version of rocker/tidyverse

---

metrics/report/report_dockerfile/collectd_scaling.R
metrics/report/report_dockerfile/dut-details.R
metrics/report/report_dockerfile/elasticsearchr.R
metrics/report/report_dockerfile/metrics_report.Rmd
metrics/report/report_dockerfile/node-info.R
metrics/report/report_dockerfile/parallel.R
metrics/report/report_dockerfile/test.R
metrics/report/report_dockerfile/tidy_scaling.R

As the metrics report gained the ability to process more test results, it never gained the ability to cope with missing test data (for instance, if you only run a single test as that is the only one you are interested in). This led to confusion and mess, as the report would end up littered with cryptic truncated R error messages, which made folks think something had gone wrong with the test/data they were actually interested in.
Clean up the R code so it handles missing files and data more gracefully, and places meaningful 'nothing found' messages into the report.
To do this involved nesting the R code into functions, as there is no other way I could find to cleanly drop out of an Rmarkdown fragment without halting the processing of the rest of the pipeline, which is not what we needed.

Make metrics pdf error reporting more graceful

---

metrics/collectd/collectd.bash
metrics/collectd/collectd.conf

Currently we loose collectd data from a node when scaling ends to a
system failure on the node - yet this data can be very helpful in root
causing the failure. This patch changes collectd configuration so that
the output will be continuously written to host filesystem instead of
the collectd container overlay that will be lost unless scaling
reaches graceful exit.
Signed-off-by: Antti Kervinen <antti.kervinen@intel.com>

metrics: change collectd output to host /opt/collectd/run

---

clr-k8s-examples/setup_system.sh

Currently the system.conf.d/proxy.conf file is saved at /usr/lib
which is the vendor path, and can be dropped by
"swupd repair --picky --force".
This PR creates the local administrator /etc/systemd/system.conf.d
directory and store the proxy.conf inside.

setup_system: use local admin path for proxy.conf

---

clr-k8s-examples/9-multi-network/Dockerfile
clr-k8s-examples/9-multi-network/README.md
clr-k8s-examples/9-multi-network/multus-sriov-ds.yaml
clr-k8s-examples/9-multi-network/sriov-conf.yaml
clr-k8s-examples/9-multi-network/test/sriov/2-pod-dpdk-ver.yaml
clr-k8s-examples/9-multi-network/test/sriov/Dockerfile

Multus CNI 3.4.2
SR-IOV CNI 2.3
SR-IOV DP  3.2
Tested as per the README. Works fine.

Update multi-net components to latest releases

---

clr-k8s-examples/Vagrantfile

Previously used IP range seems to be allocated to NASA and probably not
a good idea to use it here. Switching the private network to be part of
the IPs allocated to private networks.

Switch private network for Vagrant VMs

---

clr-k8s-examples/Vagrantfile

Hi all, 
per https://github.com/AntonioMeireles/ClearLinux-packer/issues/24 the
ClearLinux libvirt boxes default size was lowered from the previous 40G
to a more manageable 5G, having the user the ability to, at box
instantiation, to increase that value to whatever is adequate.
In order to avoid surprises in this side the Vagrantfile was modded to
have hardcoded the previous default value.
This change is forward and backward compatible as it will just be
ignored when using older boxes ( since the 'new' root volume size just
the same as original one) and will resize the box to the expected 40G in
newer ones.
Please do note that albeit code is committed, i'm not yet build new boxes with
new code - as i think it would be handy to have this merged this side first to avoid breakages
All the …

accommodate upstream libvirt boxes changes in a forward and backward way

---

clr-k8s-examples/setup_system.sh

Mask all swap targets.
This ensures no swap will be active to allow K8 testing

Disable swap before OS Update

---

clr-k8s-examples/kubeadm.yaml

Removing static cpu pinning due to confusion and complications it causes with disabling/enabling cores.

Remove static cpu from kubeadm.yaml
